complaint_system/urls.py
from django.contrib import admin
from django.urls import path
from complaints.views import create_complaint

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', create_complaint, name='create_complaint'),
]

complaints/models.py
from django.db import models
from django.contrib.auth.models import User


class Complaint(models.Model):
    DEPARTMENT_CHOICES = [
        ('B.E.', [
            ('B.E_BME', 'B.E. Bio-Medical Engineering'),
            ('B.E_CSE', 'B.E. Computer Science and Engineering'),
            ('B.E_CSE_B', 'B.E. Computer Science and Engineering (RL)'),
            ('B.E_ECE', 'B.E. Electronics and Communication Engineering'),
            ('B.E_MECH', 'B.E. Mechanical Engineering'),
        ]),
        ('B.Tech.', [
            ('BTECH_AE', 'B.Tech. Agricultural Engineering'),
            ('BTECH_AI&DS', 'B.Tech. Artificial Intelligence and Data Science'),
            ('BTECH_BT', 'B.Tech. Bio-Technology'),
            ('BTECH_IT', 'B.Tech. Information Technology'),
        ]),
        ('B.Sc.', [
            ('BSC_IT', 'B.Sc. Information Technology'),
            ('BSC_CY', 'B.Sc. Cyber Security'),
            ('BSC_AI&DS', 'B.Sc. Artificial Intelligence and Data Science'),
            ('BSC_CS', 'B.Sc. Computer Science'),
        ]),
        ('S&H', [
            ('S&H_AGRI', 'S&H - Agricultural Engineering'),
            ('S&H_AIML', 'S&H - Artificial Intelligence and Machine Learning'),
            ('S&H_AI&DS', 'S&H - Artificial Intelligence and Data Science'),
            ('S&H_BME', 'S&H - Bio-Medical Engineering'),
            ('S&H_BT', 'S&H - Biotechnology'),
            ('S&H_CSE', 'S&H - Computer Science and Engineering'),
            ('S&H_CSE_B', 'S&H - Computer Science and Engineering (RL)'),
            ('S&H_ECE', 'S&H - Electronics and Communication Engineering'),
            ('S&H_MECH', 'S&H - Mechanical Engineering'),
            ('S&H_IT', 'S&H - Information Technology'),
        ]),
    ]

    COMPLAINT_TYPES = [
        ('dresscode', 'Improper dress code'),
        ('informal_shoe', 'Informal shoe'),
        ('hairstyle', 'Improper hairstyle'),
        ('untrimmed_beard', 'Untrimmed beard'),
        ('socks_not_worn', 'Socks not worn'),
        ('shoes_not_worn', 'Shoes not worn'),
        ('blazer_not_worn', 'Blazer not worn'),
    ]

    student_id = models.CharField(max_length=16)
    staff = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    complaint_type = models.CharField(max_length=20, choices=COMPLAINT_TYPES)
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES)

    def __str__(self):
        return f"Complaint by Staff: {self.staff.username} for Student ID: {self.student_id}"

complaints/forms.py
from django import forms
from .models import Complaint


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['student_id', 'complaint_type', 'department']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['complaint_type'].widget = forms.Select(choices=Complaint.COMPLAINT_TYPES)
        self.fields['department'].widget = forms.Select(choices=Complaint.DEPARTMENT_CHOICES)

    def save(self, commit=True, staff=None):
        instance = super().save(commit=False)
        if staff:
            instance.staff = staff
        if commit:
            instance.save()
        return instance

complaints/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ComplaintForm
from .models import Complaint


def is_staff_user(user):
    return user.is_staff


@user_passes_test(is_staff_user)
def create_complaint(request):
    if request.method == 'POST':
        form = ComplaintForm(request.POST)
        if form.is_valid():
            student_id = form.cleaned_data["student_id"]
            if has_duplicate_complaint(request.user, student_id):
                messages.error(request,
                               'You have already submitted a complaint for this student today.')
            else:
                form.save(staff=request.user)
                complaints_count = Complaint.objects.filter(staff=request.user, student_id=student_id).count()
                if complaints_count >= 2:
                    messages.error(request, f'Complaint submitted successfully! Student reached {complaints_count} complaints')
                else:
                    messages.success(request, 'Complaint submitted successfully!')
            return redirect('create_complaint')
    else:
        form = ComplaintForm()

    return render(request, 'create_complaint.html', {'form': form})


def has_duplicate_complaint(user, student_id):
    today = timezone.now().date()
    return Complaint.objects.filter(staff=user, student_id=student_id, timestamp__date=today).exists()

templates/create_complaint.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/forms@0.5.7/src/index.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/quagga/0.12.1/quagga.min.js"></script>
    <title>Complaint</title>
  </head>
  <body class="bg-gray-200">
    <div class="messages">
      {% for message in messages %}
      <div
        class="{% if message.tags == 'success'%}bg-blue-500{% else%}bg-red-500{% endif %} text-white text-md p-4"
      >
        {{ message }}
      </div>
      {% endfor %}
    </div>
    <div class="form-container bg-white p-4 rounded-lg max-w-md mx-auto mt-10">
      <form
        class="mb-3"
        id="form"
        method="post"
        action="{% url 'create_complaint' %}"
      >
        {% csrf_token %}
        <h1 class="text-3xl font-bold mb-6 text-gray-600">Improper Attire</h1>
        <div class="buttonInside flex items-center mb-4">
          <input
            id="id_student_id"
            name="student_id"
            maxlength="16"
            class="form-control flex-1 mr-2 p-2 border border-gray-300 rounded"
            placeholder="Student ID"
            type="text"
            required
          />
          <button
            id="openScanner"
            type="button"
            onclick="openBarcodeScanner()"
            class="bg-blue-500 text-white p-2 rounded"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              class="w-6 h-6"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M3.75 4.875c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5A1.125 1.125 0 0 1 3.75 9.375v-4.5zm0 9.75c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5a1.125 1.125 0 0 1-1.125-1.125v-4.5zm9.75-9.75c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5A1.125 1.125 0 0 1 13.5 9.375v-4.5z"
              ></path>
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M6.75 6.75h.75v.75h-.75v-.75zm0 9.75h.75v.75h-.75v-.75zm9.75-9.75h.75v.75h-.75v-.75zm-3 6.75h.75v.75h-.75v-.75zm0 6h.75v.75h-.75v-.75zm6-6h.75v.75h-.75v-.75zm0 6h.75v.75h-.75v-.75zm-3-3h.75v.75h-.75v-.75z"
              ></path>
            </svg>
          </button>
        </div>
        <div
          id="scanner-container"
          hidden
        ></div>
        {{ form.department|add_class:'mb-6 block w-full rounded-md border-0 p-3 pr-10 text-gray-700 ring-1 ring-inset ring-gray-300 sm:text-md sm:leading-6' }}
        {{ form.complaint_type|add_class:'mb-6 block w-full rounded-md border-0 p-3 pr-10 text-gray-700 ring-1 ring-inset ring-gray-300 sm:text-md sm:leading-6' }}
        <button class="w-full bg-blue-500 text-white p-2 rounded" type="submit">
          Submit
        </button>
      </form>
    </div>
    <script>
      const scannerContainer = document.getElementById("scanner-container");

      function openBarcodeScanner() {
        Quagga.init(
          {
            inputStream: {
              name: "Live",
              type: "LiveStream",
              target: document.querySelector("#scanner-container"),
            },
            decoder: {
              readers: ["code_128_reader"],
            },
          },
          function (err) {
            if (err) {
              console.error(err);
              return;
            }
            Quagga.start();
            scannerContainer.hidden = false;
          }
        );

        Quagga.onDetected(function (result) {
          Quagga.stop();
          document.getElementById("id_student_id").value =
            result.codeResult.code;
          scannerContainer.hidden = true;
        });
      }
    </script>
  </body>
</html>